/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROODCBPDF
#define ROODCBPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooDCBPdf : public RooAbsPdf {
public:
  RooDCBPdf() {} ; 
  RooDCBPdf(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _mean,
	      RooAbsReal& _sigma,
	      RooAbsReal& _nl,
	      RooAbsReal& _al,
	      RooAbsReal& _nr,
	      RooAbsReal& _ar);
  RooDCBPdf(const RooDCBPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooDCBPdf(*this,newname); }
  inline virtual ~RooDCBPdf() { }

protected:

  RooRealProxy x ;
  RooRealProxy mean ;
  RooRealProxy sigma ;
  RooRealProxy nl ;
  RooRealProxy al ;
  RooRealProxy nr ;
  RooRealProxy ar ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooDCBPdf,1) // Your description goes here...
};
 
#endif
